"""Add datetime column to match table

Revision ID: f412641975d6
Revises: b0b0313c3459
Create Date: 2024-10-14 20:21:56.486715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f412641975d6'
down_revision: Union[str, None] = 'b0b0313c3459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'creation_date')
    # ### end Alembic commands ###
